PhotoService/PhotoService/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

PhotoService/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'),
]

blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<pk>/puslish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('users / <int:pk> /', views.users_detail, name='users_detail'),
]

mysite/urls.py
# -*- coding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),

    # main url('')로 blog.urls를 가져온다.
    path('', include('blog.urls')),

    # path('kilogram', include('kilogram.urls')),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

PhotoService/app/templates/base.html
{% load static %}

<! DOCTYPE html>
<html>

<head>
    <title> Photo is good </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
</head>

<body>
    <header>
        <div class="container">
            <h1> <a href="{% url 'app:index' %}"> Photo Site </a> </h1>
            <div class="header-menu">
                <a href=""> Photos </a>
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

PhotoService/app/templates/index.html
{% extends './base.html'%}
{% load staticfiles %}

{% block content %}

    <h2> Photo Home </h2>
    <img src="{% static 'get.gif' %}" , height="400">

{% endblock %}

PhotoService/app/templates/users_detail.html
{% extends 'app/base.html' %}
{% block content %}
    <h2 class = "user-name">@{{ user.username }}</h2>
    {{ user.is_superuser }}
    {% if user.is_superuser %}
        <p>管理者</p>
    {% else %}
        <p>一般ユーザ</p>
    {% endif %}
{% endblock %}